drop table if exists content CASCADE;

create table content (
    id bigint generated by default as identity,
    description varchar(255) not null,
    title varchar(255) not null,
    primary key (id)
);